apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbackend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbackend
  template:
    metadata:
      labels:
        app: testbackend
    spec:
      containers:
        - name: testbackend
          image: hzhuay/testbackend:v10 # or your own image
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: testbackend
  namespace: backend
spec:
  ports:
    - targetPort: 8081
      protocol: TCP
      port: 8081
      nodePort: 32222
  selector:
    app: testbackend
  type: NodePort